#启用后将回收黑曜石与空桶，并给予玩家岩浆桶
空桶点击黑曜石还原岩浆: true
#针对上述操作是否仅潜行有效
仅潜行时有效: true
#如果水/岩浆下多少格无方块，则水/岩浆不留动
禁止高空流水: true
高空流水判断格数: 3
#最后一个树叶必掉树苗
树苗掉落保底: true
#玩家掉入虚空拉回
#安装空岛插件则拉回空岛，否则拉回主世界
虚空保护: true
# 1 - 直接拉回主空岛(请将空岛传送延迟设置为0)
# 2 - 扫描附近方块，拉回到最近空岛
# 没有空岛插件或不在空岛世界就拉回到主世界
虚空保护模式: 2
#以下功能处在开发状态，可能工作异常
#将阻止黑曜石生成，并正常生成圆石
#bug较多，请谨慎使用
允许错误的刷石机: false
#以下功能尚未实现