#启用后将回收黑曜石与空桶，并给予玩家岩浆桶
空桶点击黑曜石还原岩浆: true
#针对上述操作是否仅潜行有效
仅潜行时有效: true
#如果水/岩浆下多少格无方块，则水/岩浆不留动
禁止高空流水: true
高空流水判断格数: 3
#以下功能处在开发状态，可能工作异常
#将阻止黑曜石生成，并正常生成圆石
#bug较多，请谨慎使用
允许错误的刷石机: false
#最后一个树叶必掉树苗
树苗掉落保底: true
#以下功能尚未实现
#概率综合请勿超过100
刷石机概率生成矿物: false
刷石机概率设置:
  - 16:0:10
  - 15:0:10